const Error = error{
    unexpected_result,
};

const main = fn() Error!void {
    if (true) {
    } else {
        return Error.unexpected_result;
    }
}
