const Error = error{
    unexpected_result,
};
const main = fn () Error!void {
    const a = foo(5);
    if (a != 6) {
        return Error.unexpected_result;
    }
    const b = foo(5);
    if (b != 6) {
        return Error.unexpected_result;
    }
    if (a - b != 0) {
        return Error.unexpected_result;
    }
}

const foo = fn (arg: s32) s32 {
    if (arg > 1) {
        return 6;
    } else {
        return 0;
    }
}
