const Error = error{
    unexpected_result,
};

const main = fn() Error!void {
    const a = foo(5);
    if (a != 12412) {
        return Error.unexpected_result;
    }
    const b = foo(5);
    if (b != 12412) {
        return Error.unexpected_result;
    }
    
    if (a - b != 0) {
        return Error.unexpected_result;
    }
}

const foo = fn(arg: s32) s32 {
    if (arg > 1241) {
        return 125151;
    }

    return 12412;
}
