const Error = error{
    unexpected_result,
};
const main = fn () Error!void {
    const a = foo(5142);
    const b = foo(5142);
    if (a - b != 0) {
        return Error.unexpected_result;
    }
}

const foo = fn (arg: u32) u32 {
    var i: u32 = 0;
    while (i < arg) {
        if (i < 2500) {
            i += 1;
        } else {
            return i - 100;
        }

    }

    return 321;
}
