const Error = error{
    unexpected_result,
};
const main = fn() Error!void {
    var a : s32 = 0;
    if (a != 0) {
        return Error.unexpected_result;
    }
}
